reviewking = User.create(name: "reviewking", email: "reviewking@gmail.com", password: "1234567890")
videoplayer = User.create(name: "videoplayer", email: "videoplayer@gmail.com", password: "1234567890")
billybob = User.create(name: "billybob", email: "billybob@gmail.com", password: "1234567890")
proplayer = User.create(name: "proplayer", email: "proplayer@gmail.com", password: "1234567890")
darkblade = User.create(name: "darkblade", email: "darkblade@gmail.com", password: "1234567890")
berniebro = User.create(name: "berniebro", email: "berniebro@gmail.com", password: "1234567890")
princesspeach = User.create(name: "princesspeach", email: "princesspeach@gmail.com", password: "1234567890")
concernedparent = User.create(name: "concernedparent", email: "concernedparent@gmail.com", password: "1234567890")

supermarioodyssey = Game.create(title: "Super Mario Odyssey", publisher: "Nintendo", description: "Help Mario save the Princess from the evil King Bowswer!")
kirbystarallies = Game.create(title: "Kirby Star Allies", publisher: "Nintendo", description: "Kirby needs to save the universe again from another cosmic horror threat.")
zelda = Game.create(title: "Legend of Zelda: Breath of the Wild", publisher: "Nintendo", description: "Link isn't in Kansas anymore.")
marioparty = Game.create(title: "Mario Party", publisher: "Nintendo", description: "Have fun destroying friendships in this 4 player party game.")
newsuper = Game.create(title: "New Super Mario Bros", publisher: "Nintendo", description: "Classic Mario fun!")

Game.create(title: "Resident Evil 6", publisher: "Capcom", description: "Action survival returns with more monsters to suplex.")
Game.create(title: "Resident Evil 7", publisher: "Capcom", description: "First person survival with one crazy family.")

Game.create(title: "Halo", publisher: "Microsoft", description: "Masterchief must find a way back home.")
Game.create(title: "Minecraft", publisher: "Microsoft", description: "It's a blocky world out there, becareful!")

Review.create(user: reviewking, game: supermarioodyssey, score: 5, content: "Mario is awesome!")
Review.create(user: videoplayer, game: supermarioodyssey, score: 5, content: "Game of the Year!")
Review.create(user: billybob, game: supermarioodyssey, score: 5, content: "not bad")
Review.create(user: proplayer, game: supermarioodyssey, score: 5, content: "Such a great game, would buy 100 copies if i could afford it.")
Review.create(user: darkblade, game: supermarioodyssey, score: 1, content: "were th zombies?")
Review.create(user: concernedparent, game: supermarioodyssey, score: 1, content: "Mario is teaching kids to jump on people heads and become plumbers instead of doctors")
